# Generated by Django 4.2.7 on 2025-08-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationcenter',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
